### ISSUE TITLE
单击、双击视频背景均未有反应

### ISSUE THREAD

**Issue by Sunsh4j** [xh321/LiteLoaderQQNT-Media-Local-View#1]
![动画](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/43169575/50acdd70-835e-4c55-991c-14af4856f169)

**Comment by xh321** [comment]
请问是什么系统呢？不同系统版本的QQ可能需要单独适配一下

**Comment by Sunsh4j** [comment]
> 

![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/43169575/6fd10f95-c4a0-4934-9367-f13ca9abfb5f)

**Comment by xh321** [comment]
> 

奇怪，版本和我一样，有装其他插件吗，试试禁用其他插件再看看

**Comment by Sunsh4j** [comment]
> > 
> 
> 奇怪，版本和我一样，有装其他插件吗，试试禁用其他插件再看看

也装了其他插件了，而且还挺多的🤣🤣
![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/43169575/9704441a-0863-49ee-8cf2-066c41a987ba)

**Comment by xh321** [comment]
能否全部关闭，只开我这一个插件看看？
可能有其他插件功能重复了

**Comment by Sunsh4j** [comment]
> 能否全部关闭，只开我这一个插件看看？ 可能有其他插件功能重复了

我把其他的都禁用了，只留了「核心」、「依赖」，还有禁止更新和这个插件，但是仅单机、双击视频背景还是没有反应，需要点击下载按钮才行

**Comment by xh321** [comment]
奇了怪，能否加一下联系方式我远控看看

**Comment by Sunshagon** [comment]
> 奇了怪，能否加一下联系方式我远控看看

[https://netcut.cn/QQ%E5%8F%B7

**Comment by xh321** [comment]
已经解决
