### ISSUE TITLE
多图片及GIF图片时出现问题

### ISSUE THREAD

**Issue by suiniara** [xh321/LiteLoaderQQNT-Media-Local-View#2]
![9b0d66aa41f9ac19f82483e287fa0761](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/33367461/e912d8f2-19a4-4104-b904-3f6ed1483c97)
当查看消息中存在多张图片只会打开第一张
![e6c46923460998ca4c45d397494ab7e4](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/33367461/4974e243-bca5-4cab-9c02-036e09e4f8c9)
当查看消息为GIF，则当做jpg打开

**Comment by xh321** [comment]
解决了还是？
