### ISSUE TITLE
[BUG] 当一条消息中有超过一个图片 / 视频时只能通过本地查看器查看第一张

### ISSUE THREAD

**Issue by Mindigma** [xh321/LiteLoaderQQNT-Media-Local-View#5]
_已发现一个相同症状的 issue：<https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/issues/2>。但由于已 close，本人决定再来发一次。_

---

### 环境：
macOS 12.7.3 (Chip: Apple M1)
LLQQNT v1.0.3
QQNT v6.9.25-20811
Chromium v120.0.6099.56
Electron v28.0.0
Node.js v18.18.2
「本地查看图片和视频」插件 v0.1.6

### 现象
当一条消息中有超过一个图片 / 视频时，无论是双击或者选择后再按空格预览图片 / 视频，只会调用本地查看器查看第一张图片 / 视频。

### 期望的现象
无论对哪个图片 / 视频双击或者点击再按空格，都会查看操作的那个图片 / 视频

**Comment by xh321** [comment]
已修复
