### ISSUE TITLE
合并转发的聊天记录中的图片 使用系统图片查看器功能无效

### ISSUE THREAD

**Issue by AkatsukiZhang** [xh321/LiteLoaderQQNT-Media-Local-View#6]
如题。
![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/22972499/b59bc713-63c4-4d5c-844d-aab44f7c539d)

**Comment by xh321** [comment]
收到，会进行核查

**Comment by xh321** [comment]
已修复

**Comment by AkatsukiZhang** [comment]
![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/22972499/8676a719-b9a6-4b2f-b129-170b666dfbad)
发现聊天记录内的图片也....
<del>(另外背景插件也没有应用到聊天记录界面)</del>

**Comment by xh321** [comment]
> ![image](https://private-user-images.githubusercontent.com/22972499/303829939-8676a719-b9a6-4b2f-b129-170b666dfbad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc1NjE0NjQsIm5iZiI6MTcwNzU2MTE2NCwicGF0aCI6Ii8yMjk3MjQ5OS8zMDM4Mjk5MzktODY3NmE3MTktYjlhNi00YjJmLWIxMjktMTcwYjY2NmRmYmFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjEwVDEwMzI0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRmMTRmZTkzMjFmZTJlN2RhZDc3OTRkNjU5ZmZjYjk4ZmJmZTExMzlkN2I3MmIwMjMwNzA3ODM0ZjU5NmNhMzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DFHGwOpATmY9Snsih-VAsifdjiyBrEtI0yuoDoMRCZ8) 发现聊天记录内的图片也.... ~(另外背景插件也没有应用到聊天记录界面)~

一点点修（

**Comment by AkatsukiZhang** [comment]
哈哈哈，新春快乐。
不急不急。

**Comment by xh321** [comment]
> 哈哈哈，新春快乐。 不急不急。

新春快乐~我已经更新好了
