### ISSUE TITLE
希望可以对接Windows版的QuickLook

### ISSUE THREAD

**Issue by CreeperAWA** [xh321/LiteLoaderQQNT-Media-Local-View#7]
Windows的QuickLook有两个版本，一个是从微软商店下载的版本，也就是的UWP版本，另一个是exe版本(https://github.com/QL-Win/QuickLook/releases)，希望可以对接这两个版本，并在设置里添加两个选项

1. 是否在Windows中使用内置QuickLook(exe)预览
    访达中的空格快速预览，只对安装了QuickLook exe版本的Windows有效
2.是否在Windows中使用内置QuickLook(UWP)预览
   访达中的空格快速预览，只对安装了QuickLook UWP版本的Windows有效

**Comment by xh321** [comment]
根据 https://github.com/QL-Win/QuickLook/issues/557 这很容易做到，而且不需要区分UWP版本与exe版本，这两个版本有同一个办法可以打开。我会在近期实现

**Comment by CreeperAWA** [comment]
> 根据 [QL-Win/QuickLook#557](https://github.com/QL-Win/QuickLook/issues/557) 这很容易做到，而且不需要区分 UWP 版本与 exe 版本，这两个版本有同一个办法可以打开。我会在近期实现

Thanks!

**Comment by xh321** [comment]
最新版已支持

**Comment by CreeperAWA** [comment]
> 最新版已支持

好的，谢谢
