### ISSUE TITLE
BUG Windows的QuickLook预览无法正常使用

### ISSUE THREAD

**Issue by CreeperAWA** [xh321/LiteLoaderQQNT-Media-Local-View#8]
Windows的QuickLook预览无法正常使用，不开启该功能氪正常使用系统图片查看器查看图片视频，开启后就不能使用系统图片查看器查看图片视频了，QuickLook的功能也没有

**Comment by xh321** [comment]
哦你的意思是，对图片按空格QuickLook吗？这个做不到呀，因为QQ消息没有一个“选中”的概念（除非多选，那如果一条消息有多张图片那也不行），你按空格，插件也不知道你想预览哪张图片。
所以这个QuickLook就是双击用QuickLook预览图片，而不是按空格预览，说白了就是换了个图片预览器。
如果你不是这个意思，而是说双击图片没有反应的话，这个也不应该出现，我本地测试是没问题的。需要确保你的QuickLook在后台运行中，否则无法调用。

**Comment by CreeperAWA** [comment]
> 哦你的意思是，对图片按空格 QuickLook 吗？这个做不到呀，因为 QQ 消息没有一个 “选中” 的概念（除非多选，那如果一条消息有多张图片那也不行），你按空格，插件也不知道你想预览哪张图片。 所以这个 QuickLook 就是双击用 QuickLook 预览图片，而不是按空格预览，说白了就是换了个图片预览器。 如果你不是这个意思，而是说双击图片没有反应的话，这个也不应该出现，我本地测试是没问题的。需要确保你的 QuickLook 在后台运行中，否则无法调用。

我是QuickLook v3.7.3，点一下聊天界面后双击空格不能用QuickLook预览(我确定没有输入到聊天栏里)，鼠标双击图片也没有反应，QuickLook也在后台，很奇怪

**Comment by xh321** [comment]
我和你版本一样，我是EXE安装版，商店版测试了也ok
再次说明，空格无效，只能双击图片打开
按理说如果失败会有报错的
你可以用命令行运行QQ看一下日志输出

**Comment by CreeperAWA** [comment]
> 我和你版本一样，我是EXE安装版，商店版测试了也ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行QQ看一下日志输出

我看了，你的插件没有任何输出，开关图片也没有输出

**Comment by xh321** [comment]
> > 我和你版本一样，我是EXE安装版，商店版测试了也ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行QQ看一下日志输出
> 
> 我看了，你的插件没有任何输出，开关图片也没有输出

这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。
你QQ版本多少

**Comment by CreeperAWA** [comment]
> > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > 
> > 
> > 我看了，你的插件没有任何输出，开关图片也没有输出
> 
> 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少

QQ版本9.9.7-20979 LL版本1.0.3 虽然没有输出，但是不开QuickLook的功能就能用，开了就都不能用了，只开QuickLook是用QQ自带的查看器打开

**Comment by xh321** [comment]
> > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > 
> > > 
> > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > 
> > 
> > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> 
> QQ版本9.9.7-20979 LL版本1.0.3 虽然没有输出，但是不开QuickLook的功能就能用，开了就都不能用了，只开QuickLook是用QQ自带的查看器打开

能否提供联系方式，看看远控解决一下？

**Comment by CreeperAWA** [comment]
> > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > 
> > > > 
> > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > 
> > > 
> > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > 
> > 
> > QQ版本9.9.7-20979 LL版本1.0.3 虽然没有输出，但是不开QuickLook的功能就能用，开了就都不能用了，只开QuickLook是用QQ自带的查看器打开
> 
> 能否提供联系方式，看看远控解决一下？

远控就算了吧，要不我把我QQ连带插件数据打包给你？

**Comment by xh321** [comment]
> > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > 
> > > > > 
> > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > 
> > > > 
> > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > 
> > > 
> > > QQ版本9.9.7-20979 LL版本1.0.3 虽然没有输出，但是不开QuickLook的功能就能用，开了就都不能用了，只开QuickLook是用QQ自带的查看器打开
> > 
> > 
> > 能否提供联系方式，看看远控解决一下？
> 
> 远控就算了吧，要不我把我QQ连带插件数据打包给你？

不用，你还是发日志吧，用命令行打开QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）

**Comment by CreeperAWA** [comment]
> > > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > > 
> > > > > > 
> > > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > > 
> > > > > 
> > > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > > 
> > > > 
> > > > QQ 版本 9.9.7-20979 LL 版本 1.0.3 虽然没有输出，但是不开 QuickLook 的功能就能用，开了就都不能用了，只开 QuickLook 是用 QQ 自带的查看器打开
> > > 
> > > 
> > > 能否提供联系方式，看看远控解决一下？
> > 
> > 
> > 远控就算了吧，要不我把我 QQ 连带插件数据打包给你？
> 
> 不用，你还是发日志吧，用命令行打开 QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）

我不太清楚日志输出在哪，命令行输出是乱码

**Comment by xh321** [comment]
> > > > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > > > 
> > > > > > > 
> > > > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > > > 
> > > > > > 
> > > > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > > > 
> > > > > 
> > > > > QQ 版本 9.9.7-20979 LL 版本 1.0.3 虽然没有输出，但是不开 QuickLook 的功能就能用，开了就都不能用了，只开 QuickLook 是用 QQ 自带的查看器打开
> > > > 
> > > > 
> > > > 能否提供联系方式，看看远控解决一下？
> > > 
> > > 
> > > 远控就算了吧，要不我把我 QQ 连带插件数据打包给你？
> > 
> > 
> > 不用，你还是发日志吧，用命令行打开 QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）
> 
> 我不太清楚日志输出在哪，命令行输出是乱码

用powershell执行不会乱码

**Comment by CreeperAWA** [comment]
> > > > > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > > > > 
> > > > > > > 
> > > > > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > > > > 
> > > > > > 
> > > > > > QQ 版本 9.9.7-20979 LL 版本 1.0.3 虽然没有输出，但是不开 QuickLook 的功能就能用，开了就都不能用了，只开 QuickLook 是用 QQ 自带的查看器打开
> > > > > 
> > > > > 
> > > > > 能否提供联系方式，看看远控解决一下？
> > > > 
> > > > 
> > > > 远控就算了吧，要不我把我 QQ 连带插件数据打包给你？
> > > 
> > > 
> > > 不用，你还是发日志吧，用命令行打开 QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）
> > 
> > 
> > 我不太清楚日志输出在哪，命令行输出是乱码
> 
> 用 powershell 执行不会乱码

这下看到了，开着QuickLook双击图片会有
`[34044:0223/141751.563:INFO:CONSOLE(0)] "Uncaught (in promise) Error: undefined is not iterable (cannot read property undefined)", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)`

**Comment by xh321** [comment]
> > > > > > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > > > > > 
> > > > > > > 
> > > > > > > QQ 版本 9.9.7-20979 LL 版本 1.0.3 虽然没有输出，但是不开 QuickLook 的功能就能用，开了就都不能用了，只开 QuickLook 是用 QQ 自带的查看器打开
> > > > > > 
> > > > > > 
> > > > > > 能否提供联系方式，看看远控解决一下？
> > > > > 
> > > > > 
> > > > > 远控就算了吧，要不我把我 QQ 连带插件数据打包给你？
> > > > 
> > > > 
> > > > 不用，你还是发日志吧，用命令行打开 QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）
> > > 
> > > 
> > > 我不太清楚日志输出在哪，命令行输出是乱码
> > 
> > 
> > 用 powershell 执行不会乱码
> 
> 这下看到了，开着QuickLook双击图片会有 `[34044:0223/141751.563:INFO:CONSOLE(0)] "Uncaught (in promise) Error: undefined is not iterable (cannot read property undefined)", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)`

这个报错无所谓，是因为我要阻止默认打开自带预览器的行为，QQ自己肯定会报错

我这里正常的提示是
```
[23564:0223/144003.647:INFO:CONSOLE(0)] "Uncaught (in promise) Error: undefined is not iterable (cannot read property undefined)", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
Image-Local-View: Windows QuickLook pipe connected
Image-Local-View: Windows QuickLook pipe disconnected
```

**Comment by CreeperAWA** [comment]
> > > > > > > > > > > 我和你版本一样，我是 EXE 安装版，商店版测试了也 ok 再次说明，空格无效，只能双击图片打开 按理说如果失败会有报错的 你可以用命令行运行 QQ 看一下日志输出
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 我看了，你的插件没有任何输出，开关图片也没有输出
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 这不对呀，他应该有输出的，在连接上，报错，断开连接时都有输出的，实在没有也有报错，一点信息没有不正常。 你 QQ 版本多少
> > > > > > > > 
> > > > > > > > 
> > > > > > > > QQ 版本 9.9.7-20979 LL 版本 1.0.3 虽然没有输出，但是不开 QuickLook 的功能就能用，开了就都不能用了，只开 QuickLook 是用 QQ 自带的查看器打开
> > > > > > > 
> > > > > > > 
> > > > > > > 能否提供联系方式，看看远控解决一下？
> > > > > > 
> > > > > > 
> > > > > > 远控就算了吧，要不我把我 QQ 连带插件数据打包给你？
> > > > > 
> > > > > 
> > > > > 不用，你还是发日志吧，用命令行打开 QQ 执行 `QQ --enable-logging` 完整输出贴在下面（敏感信息自行删除）
> > > > 
> > > > 
> > > > 我不太清楚日志输出在哪，命令行输出是乱码
> > > 
> > > 
> > > 用 powershell 执行不会乱码
> > 
> > 
> > 这下看到了，开着 QuickLook 双击图片会有 `[34044:0223/141751.563:INFO:CONSOLE(0)] "Uncaught (in promise) Error: undefined is not iterable (cannot read property undefined)", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)`
> 
> 这个报错无所谓，是因为我要阻止默认打开自带预览器的行为，QQ 自己肯定会报错
> 
> 我这里正常的提示是
> 
> ```
> [23564:0223/144003.647:INFO:CONSOLE(0)] "Uncaught (in promise) Error: undefined is not iterable (cannot read property undefined)", source: app://./renderer/index.html?webcontentsid=2&processGroupNS=createBlankWindow1#/main/message (0)
> Image-Local-View: Windows QuickLook pipe connected
> Image-Local-View: Windows QuickLook pipe disconnected
> ```

这是所有的控制台输出
[log.log](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/files/14382446/log.log)

**Comment by xh321** [comment]
没有有效信息，之前更新了一版，你更新后试试看

**Comment by CreeperAWA** [comment]
> 没有有效信息，之前更新了一版，你更新后试试看

我是这样设置的，请问这样正确吗？我试了还是和以前一样
![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/134939494/df9bbbb4-ecac-4dc8-aba7-96e6774d7b81)

**Comment by xh321** [comment]
设置就这几项，不会有问题的，是不是你杀毒软件拦截了？虽然按理说这也不是敏感操作，而且拦截会有报错的

**Comment by CreeperAWA** [comment]
> 设置就这几项，不会有问题的，是不是你杀毒软件拦截了？虽然按理说这也不是敏感操作，而且拦截会有报错的

我电脑没杀毒软件(

**Comment by CreeperAWA** [comment]
> > 设置就这几项，不会有问题的，是不是你杀毒软件拦截了？虽然按理说这也不是敏感操作，而且拦截会有报错的
> 
> 我电脑没杀毒软件 (

Windows自带的也没有(

**Comment by xh321** [comment]
那不然有没有可能插件冲突了？只开我这一个插件看看

**Comment by CreeperAWA** [comment]
> 那不然有没有可能插件冲突了？只开我这一个插件看看

不行

**Comment by xh321** [comment]
真没招了，不知道什么情况，如果可以重装QQ/LLQQNT试试

**Comment by CreeperAWA** [comment]
> 真没招了，不知道什么情况，如果可以重装 QQ/LLQQNT 试试

今天试了，全部重装一遍也没用，属于是不会了(

**Comment by xh321** [comment]
非常怪，你有条件换一个电脑或者让你朋友试试看吗

**Comment by CreeperAWA** [comment]
> 非常怪，你有条件换一个电脑或者让你朋友试试看吗

我朋友就可以，很神奇(

**Comment by xh321** [comment]
> > 非常怪，你有条件换一个电脑或者让你朋友试试看吗
> 
> 我朋友就可以，很神奇(

所以你可以排查对比一下你们电脑之间的差异，看看能不能找到问题原因，因为我这边也没法复现所以我也没法找原因

**Comment by CreeperAWA** [comment]
我也没动啥，今天闲得慌打开了看看居然好了

**Comment by CreeperAWA** [comment]
找到答案了，环境变量的 `PATH` 炸了就会导致无法正常打开也不报错

**Comment by xh321** [comment]
草

**Comment by CreeperAWA** [comment]
:(
QL 本身不写环境变量，但是 `System32` 之类的在环境变量，估计炸了就调用不了，就打不开
