### ISSUE TITLE
[BUG] 程序错误

### ISSUE THREAD

**Issue by cow-your-sister** [xh321/LiteLoaderQQNT-Media-Local-View#9]
![QQError_20240224_172930](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/88882901/6a4f2089-b6ea-4c4d-9b7e-4b391955a266)
实测非管理员权限运行QQNT时无论从插件市场安装这个插件还是启动主程序都会有这个报错
插件版本0.1.14，系统Win10专业版22H2
![image](https://github.com/xh321/LiteLoaderQQNT-Media-Local-View/assets/88882901/6c565f8c-557c-4b50-b71e-50dff090d7f5)

**Comment by cow-your-sister** [comment]
我这里目前只有这个插件会报错

**Comment by xh321** [comment]
这是插件商店的问题，你注意看报错，插件包下载回来还没解压，还完全没有执行我的代码。
重点是：插件商店无权在你这个路径下载我的插件安装包
可能是你llqqnt数据目录没有权限，你目前路径放在QQ的安装目录里，而QQ可能会自动给这个路径加自己的权限，导致商店插件无权操作。
为什么别的插件可以安装我不清楚，因为我没看插件商店源码。
建议
1. 把llqqnt的数据目录放在QQ安装位置以外（任意地方，只要普通用户有权限访问就行），这个通过环境变量即可设置，详见llqqnt官网
2. 去插件商店repo提issue
